stages:
 - build
 - test
 - dockerize

.deployment:
  only:
    refs:
      - main
include:
  - local: app-web/webapp-ci.yml
  - local: services-ultimap/services-ci.yml
  - local: database-car/db-image-ci.yml